### ISSUE TITLE
Duna Pioneer Module-station doesn't pull resources to its Kontainers

### ISSUE THREAD

**Issue by Smorfty** [BobPalmer/MKS#1003]
- Using a clean install with MKS, USI Life Support and Konstruction.
- Build a station with the Duna Pioneer Module piloted by a pilot and some empty Kontainers.
- Place another craft with full Kontainers beside the station.
- The station doesn't pull any resources from the nearby craft.

- Do the same thing but using a Duna Logistics Center instead and everything works fine. The station pulls half of the resources to the station.

**Comment by dgbinger** [comment]
Generally logistics should only pull into local storage where resources can be used. So for instance, if I have full kontainers of uraninite and mulch lying around, and I land a Pioneer with attached empty uraninite and mulch kontainers and an agroponics module of some kind, it should pull mulch but NOT uraninite: it'll grab mulch because it can use that, but it won't bother with the uraninite because there's no module that can use it.

(Real example: I reconfigured a spare ISM on my factory base to contain rares/exotics/RefExotics. It filled with rares from the attached drill, but didn't pull exotics from the drill rig in the next biome over. When I landed and docked a refinery configured to process refined exotics, though, it started to pull them, because now it had a use for them.)

I'm not 100% on the Log Center behavior: it may be pulling the resources because Log Centers are meant to grab everything for planetary-logistics purposes, or it may be bugged in some way, or it may just be that your Log Center craft has other modules that can use the resources in question.

**Comment by Smorfty** [comment]
In my current game the Pioneer actually **is** pulling fertilizer to it from a nearby Kontainer that the agricultural module needs.
But it also needs machinery which the Pioneer Module refuses to pull out. I've tried spawning in other kinds of MKS-containers with machinery but nothing happens.
I can, as I stated earlier, recreate the same bug/phenomenon in a clean install as well.

**Comment by dgbinger** [comment]
Oh! Machinery is weird: that "machinery" bar that some (but not all) machinery-consuming modules have isn't treated as a resource in the same way that mulch/metal/monoprop/whatever is. A kerbal* on EVA can right-click the module to "Perform maintenance," which will draw machinery from nearby storage (on-vessel or otherwise) into machinery-consuming modules.

*Might need to be an engineer, I'm not sure: I usually do this while I'm cleaning up the base anyway, so I've got an engineer doing the chores anyway.

**Comment by Smorfty** [comment]
Another thing:
In my current game, I put machinery in a container that is attached to the station and _still_ the Agricultural Module (which is also attached to the station) refuses to pull any of it.
It says "Agroponics: missing Machinery" in the tooltip. It _needs_ machinery while the container doesn't and still it won't pull any of it.
Don't know if this is a problem with the Agricultural Module, the Machinery resource or logistics in general :S

**Comment by dgbinger** [comment]
Did you try going EVA with an Engineer and using Perform Maintenance? It's fairly short-range, so you might need to walk right up to the module, but it should work.

**Comment by Smorfty** [comment]
Yes this fixed it! When I performed the maintenance, the base pulled out Machinery from the nearby Kontainer. Didn't have a clue it worked like this. It's very unintuitive and all the tutorials are so out of date. Argh!

**Comment by dgbinger** [comment]
Yeah, it's one of the most weirdly-hidden MKS features. IIRC nuclear fuel used to work similarly, haven't tried it since 0.50 so it might be different now.

If you have machinery production on the vessel, mind, it'll push into working modules so you can skip maintenance. The Ranger (expandable) workshop also offers automatic maintenance, which can be handy for complicated bases.
