### ISSUE TITLE
Storage tank cost

### ISSUE THREAD

**Issue by sopindm** [BobPalmer/MKS#292]
From config I see that emtpy storage tank costs 247000. Isn't that too much? It's about 9 times more than PDU. 
I think 2470 is fair price for this part.

Also, empty storage tank price is huge negative for some resources (try Refining-2). 
I think line
tankCost = 10000;10000;10000;10000;10000;10000;10000;10000; in MKS_Storage_Tank.cfg isn't right

Calculated right values, they are:
tankCost = 1210;26250;6250;5625;161500;1276360;215050;124950;

**Comment by koshboo** [comment]
can confirm that the above values work for the price 2470

**Comment by mmermerkaya** [comment]
Thanks for the values. They are indeed working and seem balanced.

**Comment by Ramarren** [comment]
For reference: I have made a pull request #298 with fixes to Storage Tank, Radial Tank which had similar problems, including a config which makes them work with TweakScale. It turns out that TweakScale does its own resource cost adjustment, which means that the tankCost for FSfuelSwitch have to be for empty tanks.

**Comment by BobPalmer** [comment]
Closing as this has been merged in - thanks for the PR!
