### ISSUE TITLE
Negative Costs on part purchase in Career Mode

### ISSUE THREAD

**Issue by Saelack** [BobPalmer/MKS#433]
Issue appears to be due to default loadouts and resource refunds.  For example, the UKS Pioneer Module (Surface) lists a default cost of 3,160, but comes with only 200 of it's 2000 available Machinery, and none of the 2000 Recyclables or 500 Organics allowed.  Without these resources being maxxed, the cost for the default loadout is -39,530.  When all available resources onboard are loaded, the cost comes exactly to 3,160.

**Comment by Saelack** [comment]
3,160 also appears to be the value of 200 Machinery - it is almost as if the cost of the part is set to 0 and only the value of the resources within it are being calculated.

**Comment by AvitusNerva** [comment]
After a little digging KSP seems to care about the wet cost (with all resources full, not the resource levels set in the config). It seems that KSP sets this total wet cost (TWC for brevity) like this:

TWC = cost_from_config

if( TWC <= cost_of_resources( when_full ) )
{
        TWC = cost_of_resources( at_quantities_in_config )
}

This therefore prevents TWC from being negative and could be a KSP bug because preventing the dry cost from being negative would make more sense. The listed cost is also this TWC.

In the Pioneer case:

TWC = 35000

if( TWC <= 2000*15.8(Machinery) + 2000*7(Recyclables) +  500*0.5(Organics) [=45850]  ) -> true
{
        TWC = cost_of_resources( at_quantities_in_config ) = 200 * 15.8 = 3160
}

so if you fill all resources in the Pioneer the cost is 3160

**Comment by Businfu** [comment]
Went through and looked at prices for every part in standard MKS/OKS 0.30.2
As others mentioned, It's basically the same issue for each part, their price is based on the fully loaded version. 
These parts have a negative value:

-UKS Aeroponics (orbital & surface)
-Kerbitat (orbital & surface)
-Pioneer (orbital & surface)

These parts have a big cut on the pricetag based on missing components, but must already be so expensive that they are still positive value:
-UKS Fabrication Module
-UKS Fuel Refinery
-UKS Mobile Refinery
-OKS Agriculture Module
-UKS Integrated Mobile Base

The PDU's have a similar problem, but only for the cost of Xenon

Also, a couple of oddballs: 
-the UKS Inflatable Agriculture Module.  It's price is 0 by default, and thus negative because it is also empty by default
-Logistics Hub is only priced at 4k.  Unrelated to this bug, but while on the topic of price i thought I'd mention it since it seems very low for what it does.

**Comment by BobPalmer** [comment]
Fixed in next release
