### ISSUE TITLE
Pioneer module (orbital) resulting in negative vessel cost.

### ISSUE THREAD

**Issue by tivec** [BobPalmer/MKS#460]
Take a look at the value of my research lab in this screenshot, where I have the pioneer module highlighted: http://i.imgur.com/mJau0ui.png

If I place it on top of the docking port, this is the result (Check the cost of the vessel): http://i.imgur.com/vOl1Zbm.png

It happens if I place the module individually too, costing -39530 funds.

**Comment by tivec** [comment]
If, however, I end up filling the module with Machiery, Recyclables and Organics, the funds cost will become 3160 properly.

**Comment by Businfu** [comment]
This is a known issue.  However, I wanted to repost an earlier post I made about it because it's now buried far down the list:
Went through and looked at prices for every part in standard MKS/OKS 0.30.2
As others mentioned, It's basically the same issue for each part, their price is based on the fully loaded version. 
These parts have a negative value:

-UKS Aeroponics (orbital & surface)
-Kerbitat (orbital & surface)
-Pioneer (orbital & surface)

These parts have a big cut on the pricetag based on missing components, but must already be so expensive that they are still positive value:
-UKS Fabrication Module
-UKS Fuel Refinery
-UKS Mobile Refinery
-OKS Agriculture Module
-UKS Integrated Mobile Base

The PDU's have a similar problem, but only for the cost of Xenon

Also, a couple of oddballs: 
-the UKS Inflatable Agriculture Module. It's price is 0 by default, and thus negative because it is also empty by default
-Logistics Hub is only priced at 4k. Unrelated to this bug, but while on the topic of price i thought I'd mention it since it seems very low for what it does.

**Comment by BobPalmer** [comment]
Fixed in next release
