### ISSUE TITLE
UKS Octagonal Landing Module causes CoM to shift

### ISSUE THREAD

**Issue by kjnicoletti** [BobPalmer/MKS#611]
There's a weird CoM issue with the Octagonal Landing Module. See the picture.

http://i.imgur.com/4id22cQ.jpg

**Comment by mhoram-kerbin** [comment]
As a workaround, place the Octagonal Landing Modules rotated by 180°. Although it happened to me that this also did not help - had to rebuild the whole ship in order for the CoM to be placed right.

**Comment by kjnicoletti** [comment]
That works great, thanks for the suggestion :)

**Comment by Kerbas-ad-astra** [comment]
The issue is that there's a "CoMOffset = 0,-.5,0" line in the config.  By default, the center of mass lies at the part's origin, which would be in the exact center for this piece, but the offset pulls it to the side.  Is there a reason for that line?

(For that matter, is there a reason that it's passable through one node but not the other, or passableWhenSurfaceAttached when it's not surface-attachable?)

**Comment by mhoram-kerbin** [comment]
Regarding the passable issue, I already created a pull-request: #615
