### ISSUE TITLE
Multiple modules are stored in the save file but don't need to be

### ISSUE THREAD

**Issue by jd284** [BobPalmer/MKS#772]
The following modules cause unnecessary bloat of a save file, especially since some of them are automatically added to every single part in the game:
- MKSModule
- ModuleAutoRepairer
- ModuleLogisticsConsumer
- USI_ModuleFieldRepair
- USI_ModuleRecycleablePart
- USI_ModuleRecycleBin
- USI_ModuleResourceWarehouse
If possible, they should be set to not store any save data. If this is a bug in KSP itself just ignore the ticket.

**Comment by BobPalmer** [comment]
Specifics please - all of the ones you have listed with the exception of RecycleablePart are added manually, and bits that I need there.

**Comment by jd284** [comment]
Maybe I'm misunderstanding how saving things works in KSP.
I understand that these modules need to be present in the parts configuration to function. However they have no state data or configuration of their own that would need to be saved in the savegame. So if it's possible, they should be excluded from saving, since they'll automatically be added on loading anyway.
And they're in a lot of parts so it would make savegames much smaller. I first noticed this when I wondered why my savegames with 0.33 got so much smaller (from 15MB each to under 12MB), and it was because one of the USI_ModuleRecycleablePart was dropped from each part.

**Comment by pellinor0** [comment]
The questions why there is so much persistent data that clutters the save file and seems not needed. 

From a quick look into my savegame the main source are the UI elements from the right click menu. They have lots of persistent fields, like the text next to each button. It is most obvious for modules that (presumably) should't need any persistent data, like USI_ModuleRecycleablePart. 

So I understand this as a feedback about the stock game: does the UI really need so much persistent data? For example is there any case where the text next to a button can not be determined otherwise?

**Comment by jd284** [comment]
Right, if it's the stock UI that makes the modules save this persistence data, then please ignore/close this ticket. I expected that each module could decide whether it needs to store persistence data, and possibly which data, but if this is not so then that's a stock bug and nothing you can do.

**Comment by BobPalmer** [comment]
This is stock, so there's nothing I can do with this.
