### ISSUE TITLE
Small logistics rover does not have ModulePowerCoupler.

### ISSUE THREAD

**Issue by gregbean** [BobPalmer/MKS#789]
The small logistics rover is not a power coupler.  Should it be?

**Comment by LouisB3** [comment]
I believe that ModuleLogisticsConsumer formerly allowed vessels to draw power from PDUs (even if they did not have an MKS converter, which was the original check). Since then, however, the logistics paradigm has evolved again and now each part needs to be a PowerCoupler to draw power. The mini rover _and drills_ are both affected by this - they can't draw power unless there's a separate coupler attached, such as the portable light kit.

**Comment by BobPalmer** [comment]
Added a coupler to to the rover as that makes sense.  For drills, the coupler should be on the host vessel.
