### ISSUE TITLE
ILM's resource averaging issue

### ISSUE THREAD

**Issue by sh1pman** [BobPalmer/MKS#812]
There should be an option to turn off or somehow disable the big ILM's resource averaging function. When I load a kontainer with resources to ship them somewhere else, my nearby ILM steals them back after I unlink the vessel.

**Comment by OakTree42** [comment]
Two questions. One did you lock the container? I haven't see this with ILMs with locked containers since the last patch he did.

Two, do you have a rover in the area? Because I'm noticing more issues with the rover logistics than the ILMs I /think/ but I am trying to isolate the issues a bit more and was curious.

**Comment by sh1pman** [comment]
No rover. Tried with both ILM and kontainer locked, no luck. Latesr version, of course.

**Comment by OakTree42** [comment]
Thanks, was trying to trouble shoot some of this myself and that info really helps!

**Comment by sh1pman** [comment]
Glad to have helped :)

**Comment by sh1pman** [comment]
Since I have ILMs for almost everything in my base, this happens with every resource that I try to transfer to a kontainer. 
UPD: I see that both ILMs and kontainers have the warehouse distribution module, so I think it's this module that causes all this.

**Comment by BobPalmer** [comment]
Fixed in next release
