### ISSUE TITLE
UKS resources drain upon vessel focus

### ISSUE THREAD

**Issue by RKain** [BobPalmer/MKS#831]
Anytime I focus a vessel which was running a UKS converter in the background - Nom-o-matic, Kerbitat Water purifier, or one of the Mk 3 converters - one of the input resources will immediately drain to zero when I focus the vessel after having time warped elsewhere for several days.

For example: I have an outpost with a Kerbitat (with active water purifier), 2500 water and a bunch of supplies. The life support window tells me the outpost is good for something like 2 years. I go to the space center, warp forward 45 days for unrelated reasons, then focus on this vessel. The water in the outpost proceeds to drain lightning quick, and now I've only got 130 days of life support at that outpost.

Similar things happen with supplies on a vessel with a nom-o-matic - it all becomes mulch over a matter of seconds once I refocus after warping, and I lose hundreds of days of life support.

**Comment by jd284** [comment]
The water purifier uses a lot of water (108 units per day at 100% load) to recycle supplies. So that means 2500 water will be gone in 23 days if you don't have a water drill. Sounds like it's working as intended. Using the water purifier only makes sense when you have access to water (by drilling for water or hydrates).

**Comment by RKain** [comment]
Ah, I see. It would be nice if the life support tracker reflected that, but that makes sense.
Thank you.
