### ISSUE TITLE
[1.1] The "Life support subsystem" is very confusing, + a tiny GUI bug

### ISSUE THREAD

**Issue by OzoneGrif** [BobPalmer/MKS#848]
And I find nothing in the documentation which explains the rules...

The GUI bug first : When you activate Life support on a part, the buttons "start/stop life support" won't match the current status "inactive/operational" for all the parts on the same ship.

The confusing part now... When I start life support on ships with an habitation ring and a science lab, it multiplies a lot the number of life support days for my Kerbals (I don't have any type of recycler onboard).

When I start life support on other ships, with an habitation ring, but no science lab, the life support duration isn't affected. How does it works precisely?

I use USI Life Support

**Comment by Wulfg4r** [comment]
@OzoneGrif , I cannot comment on the GUI bug, but I think I can help with the other thing you mentioned.
As stated in the [wiki](https://github.com/BobPalmer/USI-LS/wiki/Resources#recyclers), the stock science lab is a recycler with the highest efficiency (70%), so it will expand the duration of your supplies by a great deal.
Hope this helps,
- Wulf

**Comment by OzoneGrif** [comment]
Thank you Wulfg4r, I understand better now.

I don't get that design decision about the science lab. 
To me, it doesn't make sense on a gameplay level.

I'll check the parts more cautiously to find out where the recycler process is written, in game.

**Comment by Wulfg4r** [comment]
Please check first if the module was staffed. [Here](https://github.com/BobPalmer/MKS/wiki/Life-Support#parts-in-usi-kolonization-install) the MKS wiki state that recycler _must be staffed_ to function properly.
Also [here](https://github.com/BobPalmer/USI-LS/wiki/Life-Support-Example:-Mission-to-Duna) there's a sort of explanation about the use of the lab to recycle supplies: I'm not saying this is right or wrong, but it's certainly make sense for me. Maybe @BobPalmer can shed some light about this particular choice.
Last, a word of advice: I know the wikis are a sort of a mess, I know this must be tedious, but here and there between the UKS-LS wiki, the MKS wiki and the KSP forums you can find (somewhat hidden and sometimes unclear, I know) most of the infos about the inner workings of those mods. So, in order to get the most from them I think one need to spend some time reading and searching for those information on the wiki or forum threads. 
Also consider that this mod is constantly a work in progress, so between versions a lot can change; and those changes tend to reach the documentation with like 2 releases of delay :stuck_out_tongue_winking_eye:

**Comment by OzoneGrif** [comment]
I honestly searched for two hours looking everywhere to find this information, but didn't find it.
It's indeed quite a mess. :) Thanks a lot for the help.
