### ISSUE TITLE
Reactors with NFE have mismatched nominal temperatures and goal temp

### ISSUE THREAD

**Issue by sentania** [BobPalmer/MKS#852]
The reactors in the reactor pack directory have a defined coregoaltemp of 1000, however with the NFE  patch applied they have a nominal temp of 800; this mismatch results in some confusion in the right click gui of the reactors, and some oddness with the overheating status on the staging menu.

**Comment by Businfu** [comment]
I'm working on an updated NFE config as we speak.  Streetwind/Nertea made some fairly large changes to NFE reactor balance, and we worked the whole thing out so that USI reactors will be balanced against the new NFE stats.  Overall, USI reactors will have more EC/s, more fuel capacity (and therefore more loaded mass), and be more expensive.

**Comment by Businfu** [comment]
And the request has been submitted to USI Core.  I tested it out on each USI reactor and it should all be working!  Note that for consistency and balance, USI reactors Xe Production was removed, and the NFE Whirlijig can no longer make EnrichedUranium from stock Ore.
