### ISSUE TITLE
Dancing and overpowered Landing Modular Wheel

### ISSUE THREAD

**Issue by GHRyanK** [BobPalmer/MKS#875]
Acknowledged that wheels in KSP 1.1.X are problematic, but it looks like mitigation in KSP 1.1.2 did not carry over to UKS 0.40.2.1, and I didn't see an Issue entry.  The landing modular wheels dance/skitter when a vehicle is on the ground (I believe I saw a similar comment in the forums on the Karibou).  They are also extremely overpowered on acceleration and would benefit from the traction and torque control interfaces.

Thanks for the great work on adding gamer-friendly realism with all the USI products!

**Comment by Vranir** [comment]
I can confirm this issue. 

Craft dances on deployed MKS_LandingLeg and when any "rover control" is touched the craft is immediately catapulted in the appropriate direction. I also notice that the wheels never seem to (visually) touch the ground, when stationary they "dance" just above the ground.

I also have seen the Karibou comment on forums as well and it does sound similar but Karibou wheels work fine in the same install (heavily modded 1.1.2).

**Comment by Vranir** [comment]
Double checked on a clean install KSP 1.1.2. with nothing but USI Kolonization Systems v0.40.2.1, used bundled dependencies.

Issue remains.

Also tried putting stock wheels instead of  MKS_LandingWheel_Side to make sure its not some strange craft issue. Craft works fine with stock wheels. I noticed the visual bug i mention in the previous post happens on VAB launch pad but not the SPH airstrip.

Can provide output log but it seems to me there is nothing relevant in it.
