### ISSUE TITLE
Cost discrepancies with Kontainers

### ISSUE THREAD

**Issue by Tsaven** [BobPalmer/MKS#876]
When cycling through the texture options for Kontainers, the prices change wildly even if the container is empty.

Most of the 3.5m Kontainers, for example, have a base empty price of 25,740.  However, when using the Fertilizer texture the _empty_ price is 220,074, and Supplies is 838,240.  Material Kits yields a negative price of -84,760.

**Comment by matthiaswatkins** [comment]
I'll investigate this one too.

**Comment by matthiaswatkins** [comment]
I'm not sure what the issue is here; it affects all of the fuel switching Kontainers. The tank cost should be a base cost, plus an added cost that depends on the type of material it can hold. For most of the materials, no cost is added at all, even though the config specifies costs. And for the 3 materials listed above, you get those strange values.

I think this affects masses as well. Kontainers have a tankMass of 0 regardless of material type, but if I change the masses in the config, there is no corresponding change in the game; every tank has the base mass no matter what.

The config looks fine. I suspect there's either a problem with Firespitter (but I couldn't see anything wrong with the code) or with how the stock game pulls costs from the parts. (GetModuleCost())

**Comment by Chris97b** [comment]
Just wanted to mention that this seems to affect the ILMs as well. ILMs setup for EnrichedUranium or ExoticMinerals/RareMetals/SpecializedParts have a negative cost in the VAB. The config looks correct for them as far as I can tell.

**Comment by BobPalmer** [comment]
Fixed this :)
