### ISSUE TITLE
NaN error after starting Agroponics on Duna Module

### ISSUE THREAD

**Issue by andreszlima** [BobPalmer/MKS#973]
This bug happened on your stream some days ago. Things just disappear after clicking on 'Start Agroponics' on Duna module. This happened 100% of the time after activating "greenhouse" before on a ranger module.  
Spam of error on log:

---

(Filename:  Line: 82)

Look rotation viewing vector is zero

(Filename:  Line: 82)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Duna.Agriculture/model/UmbraSpaceIndustries/MKS/Assets/DunaGeneric(Clone)/GenericModule/collider"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Duna.Agriculture/model/UmbraSpaceIndustries/MKS/Assets/DunaGeneric(Clone)/GenericModule/Pin/TopShaft/BottomShaft/Foot"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Duna.Agriculture/model/UmbraSpaceIndustries/MKS/Assets/DunaGeneric(Clone)/GenericModule/Pin_001/TopShaft_001/BottomShaft_001/Foot_001"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Duna.Agriculture/model/UmbraSpaceIndustries/MKS/Assets/DunaGeneric(Clone)/GenericModule/Pin_002/TopShaft_002/BottomShaft_002/Foot_002"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Duna.Agriculture/model/UmbraSpaceIndustries/MKS/Assets/DunaGeneric(Clone)/GenericModule/Pin_003/TopShaft_003/BottomShaft_003/Foot_003"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Ranger.AgModule/model/UmbraSpaceIndustries/MKS/Assets/Ranger_AgModule(Clone)/AgModule/Space/COLL"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Ranger.AgModule/model/UmbraSpaceIndustries/MKS/Assets/Ranger_AgModule(Clone)/AgModule/Space/COLL"

(Filename:  Line: 163)

Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "Ranger.ISM/model/UmbraSpaceIndustries/MKS/Assets/Ranger_ILM(Clone)/MiniILM/DomeC/COLL"

(Filename:  Line: 163)

Look rotation viewing vector is zero

---

[output_log.txt](https://github.com/BobPalmer/MKS/files/548919/output_log.txt)

**Comment by scorpion451** [comment]
Having the exact same issue when trying to start production of polymers on my Minumus base's new refinery module.

Actually managed to get a proper quit-save for this error (semi-intentional, but hooray for backups), and KSP produced the following crash log when attempting to load it:
[KSP_log_after_NaN_error_when_starting_polymer_production.txt](https://github.com/BobPalmer/MKS/files/553784/KSP_log_after_NaN_error_when_starting_polymer_production.txt)

On the off chance this makes a difference, all the pieces of my base are docked together with KIS/KAS winches , mostly through a central anchor-ball hub, but also a daisy chain of connections to a pair of cargo-dropships-turned-solar-farms and a Power Distributor. (Yeah, I know..."kick me" sign for the kraken. Green kerbals need polymers badly to establish proper distributed base that doesn't have drills stuck in random places without internal storage. X3)

**Comment by tarheel1999** [comment]
Starting and stopping the Duna Ag Module with no other parts is sufficient to cause this.
https://github.com/BobPalmer/MKS/issues/978

**Comment by scorpion451** [comment]
As an update, this workaround mentioned in the forums let me start my refinery without incident: 
* deactivate all efficiency modules in the area 
 * This includes modules on other vessels in the loaded region, connected or not.
 * Not sure if you just have to turn off the ones with the same tags (ie just the [greenhouse]s or [smelters])  or all of them; I turned off all of mine just to be safe. 
* F5 and F9 to reload 
* start production module
* turn on efficiency modules
No kabooms.

**Comment by BobPalmer** [comment]
This will be fixed in the next release.
